### PR TITLE
Update Plane.java

### PR DESCRIPTION
**Pull request by BluesLackSheep**
So, I fixed the code in reservingSeats method. If there is still any error in this method, just let me kill myself.

### CODE REVIEW

**Comment by Botanahmad** [comment]
Yi it doesn't let me add it, it says conflict. We need somewhere we can message each other message back

**Comment by BluesLackSheep** [comment]
by using Messenger?
it is a facebook app

**Comment by Botanahmad** [comment]
sureee whats your facebook

**Comment by BluesLackSheep** [comment]
just search Yi Zhang

**Comment by BluesLackSheep** [comment]
in GHS

**Comment by Botanahmad** [comment]
does it have a snapchat picture?

**Comment by BluesLackSheep** [comment]
yes

**Comment by Botanahmad** [comment]
ok i added u

**Comment by Botanahmad** [comment]
wont let me message you until we are friends

**Comment by BluesLackSheep** [comment]
k

**Comment by BluesLackSheep** [comment]
accepted

**Pull request closed without merging**
